onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - lefthook
  - prisma
  - unrs-resolver

minimumReleaseAge: 1440 # 1 day
